### ISSUE TITLE
Define CRD

### ISSUE THREAD

**Issue by loganmc10** [RHsyseng/cluster-relocation-operator#4]
We need to define the CRD, here is a starting point:
```
apiVersion: "rhsyseng.github.io/v1beta1"
kind: ClusterRelocation
metadata:
  name: cluster
spec:
  domain: "thenew.domain.com"
  apiCertRef: # Optional, generate self-signed cert if not provided
    name: <some_tls_secret>
    namespace: <some_namespace>
  ingressCertRef: # Optional, generate self-signed cert if not provided
    name: <some_tls_secret>
    namespace: <some_namespace>
  pullSecretRef: # Optional, allows setting a new cluster-wide pull secret
    name: <some_dockercfg_secret>
    namespace: <some_namespace>
  sshKey: | # Optional, allows setting a new SSH key for the 'core' user
    somekey
  registryCertRef: # Optional, allows adding a cert for a new trusted registry
    name: <some_tls_secret>
    namespace: <some_namespace>
  imageContentSources: # Optional, allows configuring a new mirror
    - mirrors:
        - <mirror_hostname>:8443/openshift/release
      source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    - mirrors:
        - <mirror_hostname>:8443/openshift/release-images
      source: quay.io/openshift-release-dev/ocp-release
    - mirrors:
        - <mirror_hostname>:8443/multicluster-engine
      source: registry.redhat.io/multicluster-engine
  catalogSoures: # Optional, sets up new CatalogSources
    - name: redhat-operators
      image: <mirror_hostname>:8443/redhat/redhat-operator-index:v4.12
```

I envision this as a cluster-scoped resource (no namespace), and it needs to have the name "cluster", since there can really only be one. This is similar to how other OpenShift cluster-wide CRDs work.
